# Generated by Django 5.0.1 on 2024-07-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/media/user_images/default.png', upload_to='user_images'),
        ),
    ]
