version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: images/DjangoDockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./stepmania/staticfiles:/app/staticfiles
      - ./stepmania/media:/app/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
