# Generated by Django 5.0.1 on 2024-01-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('availability', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
    ]
