# Generated by Django 5.0.1 on 2024-07-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='shoes',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
